
version: "3.8"
services:
  web:
    image: nginx:stable-alpine
    container_name: vuln-web
    volumes:
      - ./www:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"
    networks:
      - lab-net

  attacker:
    image: alpine:3.18
    container_name: attacker
    depends_on:
      - web
    networks:
      - lab-net
    command: ["/bin/sh","-c","apk add --no-cache curl && /attacker/scripts/scan.sh"]
    volumes:
      - ./attacker:/attacker:ro

networks:
  lab-net:
    driver: bridge
